bracketSpacing: true
endOfLine: lf
printWidth: 80
singleQuote: false
tabWidth: 2
trailingComma: es5
semi: true

importOrder: ["<THIRD_PARTY_MODULES>", "^[./]"]
importOrderSeparation: true
importOrderSortSpecifiers: true
